models.py
from exts import db
from werkzeug.security import generate_password_hash, check_password_hash


class UserModel(db.Model):
    __tablename__ = "user"
    uid = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False, default="1234")

    def __init__(self, username: str, password: str):
        self.username = username
        self.password = generate_password_hash(password)


class RankingModel(db.Model):
    __tablename__ = "ranking"
    rank_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    rank_user = db.Column(db.String(200), db.ForeignKey('user.username'))
    wrong_moves = db.Column(db.Integer, nullable=False)

blueprints/forms.py
import wtforms
from wtforms.validators import length, EqualTo


class RegisterForm(wtforms.Form):
    username = wtforms.StringField(validators=[length(min=3, max=20)])
    password = wtforms.StringField(validators=[length(min=3, max=20)])
    password_confirm = wtforms.StringField(validators=[EqualTo("password")])


class LogingForm(wtforms.Form):
    username = wtforms.StringField(validators=[length(min=3, max=20)])
    password = wtforms.StringField(validators=[length(min=3, max=20)])


class SubmitForm(wtforms.Form):
    wrong_moves = wtforms.IntegerField()

app.py
"""
CITS5507 Project2
"""
from flask import Flask, g, session, render_template
from flask_migrate import Migrate
from models import *

import config
from exts import db

from blueprints import game_bp
from blueprints import user_bp

app = Flask(__name__)
app.config.from_object(config)
db.init_app(app)
migrate = Migrate(app, db)

app.register_blueprint(game_bp)
app.register_blueprint(user_bp)


# db.create_all()

@app.before_request
def before_request():
    user_id = session.get('user_id')
    if user_id:
        try:
            user = UserModel.query.get(user_id)
            # setattr(g, "user", user)
            g.user = user
        except:
            g.user = None


@app.context_processor
def context_processor():
    if hasattr(g, "user"):
        return {"user": g.user}
    else:
        return {}


@app.errorhandler(404)
def page_unauthorized(error):
    return render_template('404.html', error_info=error), 404

if __name__ == '__main__':
    app.run()

blueprints/__init__.py
from .game import bp as game_bp
from .user import bp as user_bp

blueprints/game.py
from flask import Blueprint, render_template
from decorators import login_required

bp = Blueprint("game", __name__, url_prefix="")


@bp.route("/play")
@login_required
def play():
    return render_template('game_play.html')


@bp.route("/")
def intro():
    return render_template('intro.html')

blueprints/user.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, g, jsonify
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash

from blueprints.forms import RegisterForm, LogingForm, SubmitForm
from exts import db
from models import UserModel,RankingModel

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/login", methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LogingForm(request.form)
        if form.validate():
            username = form.username.data
            password = form.password.data
            user = UserModel.query.filter_by(username=username).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.uid
                return redirect("/")
            else:
                flash("Password doesn't match the username!")
                return redirect(url_for("user.login"))
        else:
            flash("Username or Password format error!")
            return redirect(url_for("user.login"))


@bp.route("/register", methods=['POST', 'GET'])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            username = form.username.data
            password = form.password.data
            user = UserModel(username=username, password=password)
            try:
                db.session.add(user)
                db.session.commit()
            except IntegrityError:
                flash("The username cannot be used because it has a duplicate name.")
                return redirect(url_for("user.register"))
            return redirect(url_for("user.login"))
        else:
            flash("Format error")
            return redirect(url_for("user.register"))


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("user.login"))


@bp.route("/ranking", methods=['POST', 'GET'])
def ranking():
    if request.method == "GET":
        return render_template("404.html")
    else:
        form = SubmitForm(request.form)
        name = g.user.username
        wrong_moves = form.wrong_moves.data
        ranking = RankingModel(rank_user=name, wrong_moves=wrong_moves)
        db.session.add(ranking)
        db.session.commit()
        return redirect(url_for("user.show_ranking"))


@bp.route("/showranking")
def show_ranking():
    rv = RankingModel.query.filter_by(rank_user=g.user.username).order_by(RankingModel.wrong_moves).all()
    payload = []
    content = {}
    for result in rv:
        content = {'username': result.rank_user, 'wrong_moves':result.wrong_moves}
        payload.append(content)
        content = {}
    return render_template("ranking.html", context=jsonify(payload))


@bp.route("/allranking")
def all_ranking():
    rv = RankingModel.query.order_by(RankingModel.wrong_moves).all()
    payload = []
    content = {}
    for result in rv:
        content = {'username': result.rank_user, 'wrong_moves': result.wrong_moves}
        payload.append(content)
        content = {}
    return render_template("ranking.html", context=jsonify(payload))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!--    bootstrap-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.css') }}">
    <!--    css style-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    <!--    font style-->
    <!-- font-style:Montserrat -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;600&display=swap" rel="stylesheet">
    {% block head %}{% endblock %}
</head>

<body>
    <div class="container-fluid navbarcontainer ">
        <nav class="navbar navbar-expand-lg navbar-light  ">
            <!-- to make a drop down button -->
            <a class="navbar-brand" style="color:rgb(241, 241, 244);" href="{{ url_for('game.intro') }}">
                Sudoku</a>
            <div class="collapse navbar-collapse" id="navbar-nav"></div>
            <!-- id in data target should be id of the navbar div below -->
            <button type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" class="navbar-toggler"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse  " id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('game.play') }}">Start Game</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('user.all_ranking') }}">Ranking</a>
                    </li>
                    {% if user %}
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('user.show_ranking') }}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page" id="logout"
                            href="{{ url_for('user.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a id="navlogin" class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('user.login') }}">Login</a>
                    </li>
                    <li class="nav-item active">
                        <a id="navsignup" class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('user.register') }}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

{% block body %}{% endblock %}

    <footer class="bg-light text-center text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3">
            © 2022 Copyright: CITS5505 Sudoku.com
        </div>
        <!-- Copyright -->
    </footer>

<!--    <div class="container-fluid pt-5 mt-5"></div>-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5d90e8600e.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</body>

</html>

templates/game_play.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sudoku</title>
    <!--    bootstrap-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.css') }}">
    <!--    css style-->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/game_play.css') }}">
    <!-- font-style:Montserrat -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;600&display=swap" rel="stylesheet">


</head>

<body>
    <div class="container-fluid navbarcontainer ">
        <nav class="navbar navbar-expand-lg navbar-light  ">
            <!-- to make a drop down button -->
            <a class="navbar-brand" style="color:rgb(241, 241, 244);" href="{{ url_for('game.intro') }}">
                Sudoku</a>
            <div class="collapse navbar-collapse" id="navbar-nav"></div>
            <!-- id in data target should be id of the navbar div below -->
            <button type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" class="navbar-toggler"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse  " id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page" id="navstartgame"
                            href="{{ url_for('game.play') }}">Start Game</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);"aria-current="page"
                            href="{{ url_for('user.all_ranking') }}">Ranking</a>
                    </li>
                    {% if user %}
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('user.show_ranking') }}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page" id="logout"
                            href="{{ url_for('user.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('user.login') }}">Login</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" style="color:rgb(241, 241, 244);" aria-current="page"
                            href="{{ url_for('user.register') }}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>

        <!-- create a board -->
    <div class="container-fluid gamesection">


        <div class="row">

            <div class="leftscetion col-lg-6 " id="board"></div>
            <div class="rightsection col col-lg-6">
                <div class="startgame">
                    <button class="newgamebutton">NEW GAME</button>
                    <!-- create digits that can be selected -->

                    <div id="digits">
                        <div id="1" class="digit">1</div>
                        <div id="2" class="digit">2</div>
                        <div id="3" class="digit">3</div>
                        <div id="4" class="digit">4</div>
                        <div id="5" class="digit">5</div>
                        <div id="6" class="digit">6</div>
                        <div id="7" class="digit">7</div>
                        <div id="8" class="digit">8</div>
                        <div id="9" class="digit">9</div>
                    </div>
                </div>
                <!-- result and submit section -->
                <div id="result">
                    <h1 id="wrongmoves">Wrong Moves</h1>
                    <h2 id="errors">0</h2>
                    <button class="submitbutton">SUBMIT</button>
                </div>
            </div>
        </div>
    </div>
    <footer class="bg-light text-center text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" >
          © 2022 Copyright: CITS5505 Sudoku.com
        </div>
        <!-- Copyright -->
      </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5d90e8600e.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{{ url_for('static',filename='js/index.js') }}"></script>

</body>

</html>

templates/intro.html
{% extends "base.html" %}

{% block title %}Intro{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/intro.css') }}">
<!--font style for features title-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
{% endblock %}




{% block body %}
    <div class="container-fluid title">
      <!-- Title -->
      <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12">
          <h1>Play sudoku puzzles online for free!</h1>
          <!-- make sure to add btn first, then add style-->
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12">
          <img class="title-image"
            src="{{ url_for('static',filename='img/sudokuboard.jpg') }}"
            alt="iphone-mockup">
        </div>
      </div>
    </div>
<!--   Features-->
  <div class="container-fluid ">
    <div class="row">
      <div class="col-lg-4 feature-sec ">
        <i class="icon fa-solid fa-circle-check fa-4x"></i>
        <h3 class="feature-title">Boost Logical Thinking</h3>
        <p>Sudoku is not a mathematical game. It requires absolutely no arithmetic skills, but it does require logical reasoning. </p>
      </div>
      <div class="col-lg-4 feature-sec ">
        <i class="icon fa-solid fa-bullseye fa-4x"></i>
        <h3 class="feature-title">Improve Concentration</h3>
        <p>Puzzlers who enjoy the game very quickly learn to focus their concentration on what they are doing in that very moment. </p>

      </div>
      <div class="col-lg-4 feature-sec">
        <i class="icon fa-solid fa-heart fa-4x"></i>
        <h3 class="feature-title">Gain Accomplishment</h3>
        <p>Completing Sudoku will make a person feeling motivated and positive.</p>
      </div>
    </div>
    </div>

<!--Rules-->
<div class="container-fluid rules">
  <div class="row">
    <div class="col-lg-6 rules-sec ">
      <h2 class="rules-title">Rule 1 - Each row must contain the numbers from 1 to 9, without repetitions</h2>
      <p>The player must focus on filling each row of the grid while ensuring there are no duplicated numbers. The
        placement order of the digits is irrelevant.

        Every puzzle, regardless of the difficulty level, begins with allocated numbers on the grid. The player should
        use these numbers as clues to find which digits are missing in each row.</p>
      <a class="refer" href="https://sudoku.com/how-to-play/sudoku-rules-for-complete-beginners/#:~:text=Sudoku%20Rule%20%E2%84%96%201%3A%20Use%20Numbers%201%2D9&text=Within%20the%20rows%20and%20c
    olumns,the%20row%2C%20column%20or%20square.">Learn More</a>
    </div>
    <div class="col-lg-6 rules-sec ">
      <h2 class="rules-title">Rule 2 - Each column must contain the numbers from 1 to 9, without repetitions</h2>
      <p>The Sudoku rules for the columns on the grid are exactly the same as for the rows. The player must also fill
        these with the numbers from 1 to 9, making sure each digit occurs only once per column.

        The numbers allocated at the beginning of the puzzle work as clues to find which digits are missing in each
        column and their position. </p>
       <a class="refer" href="https://sudoku.com/how-to-play/sudoku-rules-for-complete-beginners/#:~:text=Sudoku%20Rule%20%E2%84%96%201%3A%20Use%20Numbers%201%2D9&text=Within%20the%20rows%20and%20c
    olumns,the%20row%2C%20column%20or%20square.">Learn More</a>
    </div>
    <div class="col-lg-6 rules-sec ">
      <h2 class="rules-title">Rule 3 - The digits can only occur once per block (nonet)</h2>
      <p>A regular 9 x 9 grid is divided into 9 smaller blocks of 3 x 3, also known as nonets. The numbers from 1 to 9
        can only occur once per nonet.

        In practice, this means that the process of filling the rows and columns without duplicated digits finds inside
        each block another restriction to the numbers’ positioning. </p>
       <a class="refer" href="https://sudoku.com/how-to-play/sudoku-rules-for-complete-beginners/#:~:text=Sudoku%20Rule%20%E2%84%96%201%3A%20Use%20Numbers%201%2D9&text=Within%20the%20rows%20and%20c
    olumns,the%20row%2C%20column%20or%20square.">Learn More</a>
    </div>
    <div class="col-lg-6 rules-sec ">
      <h2 class="rules-title">Rule 4 - The sum of every single row, column and nonet must equal 45</h2>
      <p>To find out which numbers are missing from each row, column or block or if there are any duplicates, the player
        can simply count or flex their math skills and sum the numbers.
        When the digits occur only once, the total of each row, column and group must be of 45. </p>
       <a class="refer" href="https://sudoku.com/how-to-play/sudoku-rules-for-complete-beginners/#:~:text=Sudoku%20Rule%20%E2%84%96%201%3A%20Use%20Numbers%201%2D9&text=Within%20the%20rows%20and%20c
    olumns,the%20row%2C%20column%20or%20square.">Learn More</a>
    </div>
  </div>
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block head %}
 <link rel="stylesheet" href="{{ url_for('static',filename='css/login.css') }}">
{% endblock %}

{% block body %}
 <div class="container-fliud inputsec">
    <div class="row mt-2">
        <div class="col"></div>
        <div class="col ">
            <form method="post" action="{{ url_for("user.login") }}">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="mb-3 d-grid">
                    <button type="submit" class="btn btn-primary" >Login</button>
                </div>
                {% for message in get_flashed_messages() %}
                    <div class="mb-3 text-danger">
                        {{ message }}
                    </div>
                {% endfor %}
            </form>
        </div>
        <div class="col"></div>
    </div>
     </div>

{% endblock %}

templates/ranking.html
{% extends "base.html" %}

{% block title %}Ranking{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/ranking.css') }}">
    <script type="text/javascript">
        window.onload = function () {
            populateData({{ context.json|safe }})
        }

        function populateData(packJson) {
            var cnt = 0;
            for (var i = 0; i < packJson.length; i++) {
                cnt++;
                $("#ranking > tbody").append("<tr></tr>");
                $("#ranking tr:last").append("<td>" + cnt + "</td>");
                $("#ranking tr:last").append("<td>" + packJson[i].username + "</td>");
                $("#ranking tr:last").append("<td>" + packJson[i].wrong_moves + "</td>");
            }

        }
    </script>

{% endblock %}

{% block body %}

    <div id="dataid" d="{{ context.json }}" style="display:none"></div>

    <section class="container-fluid tablestyle p-5  ">
        <div class="container ">
            <table id="ranking" class="table table-hover text-center" width="100%">
                <thead>
                <tr class="table-title">
                    <th>No.</th>
                    <th>Name</th>
                    <th>Wrong Moves</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>

    </section>



{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block head %}
 <link rel="stylesheet" href="{{ url_for('static',filename='css/register.css') }}">
{% endblock %}

{% block body %}
 <div class="container-fliud inputsec">
    <div class="row mt-2">
        <div class="col "></div>
        <div class="col">
            <form method="post" action="{{ url_for("user.register") }}">
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control" name="password_confirm">
                </div>
                <div class="mb-3 d-grid">
                    <button type="submit" class="btn btn-primary" >Sign Up</button>
                </div>
                {% for message in get_flashed_messages() %}
                    <div class="mb-3 text-danger">
                        {{ message }}
                    </div>
                {% endfor %}
            </form>
        </div>
        <div class="col"></div>
    </div>
 </div>
{% endblock %}